"""Shared hard runtimes and leases for Modal's durable workers.

A lease must outlive the container's hard execution timeout. A provider call can
outlast a worker's soft deadline, so that deadline cannot be the lease bound.
"""

WORKER_LEASE_GRACE_SECONDS = 300

VALIDATION_WORKER_TIMEOUT_SECONDS = 2400
COLLECTION_WORKER_TIMEOUT_SECONDS = 2400
VULNERABILITY_IMPORT_WORKER_TIMEOUT_SECONDS = 1200

VALIDATION_WORKER_LEASE_SECONDS = VALIDATION_WORKER_TIMEOUT_SECONDS + WORKER_LEASE_GRACE_SECONDS
COLLECTION_WORKER_LEASE_SECONDS = COLLECTION_WORKER_TIMEOUT_SECONDS + WORKER_LEASE_GRACE_SECONDS
VULNERABILITY_IMPORT_WORKER_LEASE_SECONDS = (
    VULNERABILITY_IMPORT_WORKER_TIMEOUT_SECONDS + WORKER_LEASE_GRACE_SECONDS
)
