"""Deterministic runtime detection rules."""

from denali.detections.engine import (
    AWS_RISKY_SEQUENCE_RULE_UID,
    AWS_UNAPPROVED_TOOL_RULE_UID,
    AWS_UNDECLARED_MODEL_RULE_UID,
    ENTRA_CONSENT_RULE_UID,
    ENTRA_FAILURE_RULE_UID,
    OPENSHELL_BOUNDARY_RULE_UID,
    OPENSHELL_CREDENTIAL_DESTINATION_RULE_UID,
    OPENSHELL_PROVER_AUTHORITY_RULE_UID,
    RUNTIME_DENIAL_PATH_RULE_UID,
    RUNTIME_POLICY_MISMATCH_RULE_UID,
    RUNTIME_TELEMETRY_INTEGRITY_RULE_UID,
    UNREVIEWED_MODEL_RULE_UID,
    evaluate_aws_risky_action_sequence,
    evaluate_aws_unapproved_tool_invocation,
    evaluate_aws_undeclared_model_invocation,
    evaluate_denials_followed_by_alternate_path,
    evaluate_effective_policy_exceeds_boundary,
    evaluate_new_credentialed_destination,
    evaluate_prover_authority_gap,
    evaluate_repeated_failed_ai_signins,
    evaluate_runtime_policy_mismatch,
    evaluate_telemetry_interruption_or_contradiction,
    evaluate_unreviewed_ai_consent,
    evaluate_unreviewed_model_invocation,
)

__all__ = [
    "AWS_RISKY_SEQUENCE_RULE_UID",
    "AWS_UNAPPROVED_TOOL_RULE_UID",
    "AWS_UNDECLARED_MODEL_RULE_UID",
    "ENTRA_CONSENT_RULE_UID",
    "ENTRA_FAILURE_RULE_UID",
    "OPENSHELL_BOUNDARY_RULE_UID",
    "OPENSHELL_CREDENTIAL_DESTINATION_RULE_UID",
    "OPENSHELL_PROVER_AUTHORITY_RULE_UID",
    "RUNTIME_DENIAL_PATH_RULE_UID",
    "RUNTIME_POLICY_MISMATCH_RULE_UID",
    "RUNTIME_TELEMETRY_INTEGRITY_RULE_UID",
    "UNREVIEWED_MODEL_RULE_UID",
    "evaluate_aws_risky_action_sequence",
    "evaluate_aws_unapproved_tool_invocation",
    "evaluate_aws_undeclared_model_invocation",
    "evaluate_denials_followed_by_alternate_path",
    "evaluate_effective_policy_exceeds_boundary",
    "evaluate_new_credentialed_destination",
    "evaluate_prover_authority_gap",
    "evaluate_repeated_failed_ai_signins",
    "evaluate_runtime_policy_mismatch",
    "evaluate_telemetry_interruption_or_contradiction",
    "evaluate_unreviewed_ai_consent",
    "evaluate_unreviewed_model_invocation",
]
