"""Self-service provider connection contracts."""

from denali.connections.aws import (
    AWS_COVERAGE_AUTOMATIC,
    AWS_COVERAGE_SELECTED,
    AWS_SCOPE_AGENTCORE,
    AWS_SCOPE_BEDROCK_ACTIVITY,
    AWS_SCOPE_BEDROCK_AGENTS,
    AWS_SCOPE_BEDROCK_LOGGING,
    AWS_SCOPE_CODE_TO_CLOUD,
    AWS_SCOPES,
    AwsConnectionValidator,
    aws_connection_coverage_plan,
    aws_coverage_plan,
    render_cloudformation,
)
from denali.connections.aws_onboarding import (
    AWS_ONBOARDING_TEMPLATE_VERSION,
    AwsCloudFormationLauncher,
)
from denali.connections.azure import (
    AZURE_CLOUD_PUBLIC,
    AZURE_SCOPE_AI_ACTIVITY,
    AZURE_SCOPE_AI_PLATFORM,
    AZURE_SCOPE_AI_SERVICES,
    AZURE_SCOPE_CODE_TO_CLOUD,
    AZURE_SCOPES,
    AzureConnectionValidator,
    azure_coverage_plan,
)
from denali.connections.azure_onboarding import (
    AZURE_ONBOARDING_SCRIPT_VERSION,
    AzureSetupScriptLauncher,
    render_setup_script,
)
from denali.connections.entra import (
    ENTRA_SCOPE_APPLICATIONS,
    ENTRA_SCOPE_DIRECTORY_AUDITS,
    ENTRA_SCOPE_PERMISSIONS,
    ENTRA_SCOPE_SIGN_INS,
    ENTRA_SCOPES,
    EntraAdminConsentClient,
    EntraConnectionValidator,
    entra_coverage_plan,
)
from denali.connections.gcp import (
    GCP_SCOPE_AGENT_BUILDER,
    GCP_SCOPE_AI_ACTIVITY,
    GCP_SCOPE_CODE_TO_CLOUD,
    GCP_SCOPE_VERTEX_AI,
    GCP_SCOPES,
    GcpConnectionValidator,
    gcp_coverage_plan,
)
from denali.connections.gcp_onboarding import (
    GCP_ONBOARDING_SCRIPT_VERSION,
    GcpConnectionPrincipalProvisioner,
    GcpSetupScriptLauncher,
    render_gcp_setup_script,
)
from denali.connections.github import (
    GITHUB_REQUIRED_PERMISSIONS,
    GITHUB_SCOPE_ACTIONS_WORKFLOWS,
    GITHUB_SCOPE_REPOSITORY_CONTENTS,
    GITHUB_SCOPE_REPOSITORY_METADATA,
    GITHUB_SCOPES,
    GitHubAppClient,
    GitHubConnectionValidator,
    github_coverage_plan,
)

__all__ = [
    "AWS_COVERAGE_AUTOMATIC",
    "AWS_COVERAGE_SELECTED",
    "AWS_SCOPE_AGENTCORE",
    "AWS_SCOPE_BEDROCK_ACTIVITY",
    "AWS_SCOPE_BEDROCK_AGENTS",
    "AWS_SCOPE_BEDROCK_LOGGING",
    "AWS_SCOPE_CODE_TO_CLOUD",
    "AWS_SCOPES",
    "AWS_ONBOARDING_TEMPLATE_VERSION",
    "AwsCloudFormationLauncher",
    "AwsConnectionValidator",
    "AZURE_CLOUD_PUBLIC",
    "AZURE_ONBOARDING_SCRIPT_VERSION",
    "AZURE_SCOPE_AI_ACTIVITY",
    "AZURE_SCOPE_AI_PLATFORM",
    "AZURE_SCOPE_AI_SERVICES",
    "AZURE_SCOPE_CODE_TO_CLOUD",
    "AZURE_SCOPES",
    "AzureConnectionValidator",
    "AzureSetupScriptLauncher",
    "GCP_ONBOARDING_SCRIPT_VERSION",
    "GCP_SCOPE_AGENT_BUILDER",
    "GCP_SCOPE_AI_ACTIVITY",
    "GCP_SCOPE_CODE_TO_CLOUD",
    "GCP_SCOPE_VERTEX_AI",
    "GCP_SCOPES",
    "GcpConnectionPrincipalProvisioner",
    "GcpConnectionValidator",
    "GcpSetupScriptLauncher",
    "GITHUB_REQUIRED_PERMISSIONS",
    "GITHUB_SCOPE_ACTIONS_WORKFLOWS",
    "GITHUB_SCOPE_REPOSITORY_CONTENTS",
    "GITHUB_SCOPE_REPOSITORY_METADATA",
    "GITHUB_SCOPES",
    "GitHubAppClient",
    "GitHubConnectionValidator",
    "ENTRA_SCOPE_APPLICATIONS",
    "ENTRA_SCOPE_DIRECTORY_AUDITS",
    "ENTRA_SCOPE_PERMISSIONS",
    "ENTRA_SCOPE_SIGN_INS",
    "ENTRA_SCOPES",
    "EntraAdminConsentClient",
    "EntraConnectionValidator",
    "aws_connection_coverage_plan",
    "aws_coverage_plan",
    "azure_coverage_plan",
    "gcp_coverage_plan",
    "github_coverage_plan",
    "entra_coverage_plan",
    "render_cloudformation",
    "render_setup_script",
    "render_gcp_setup_script",
]
